import type { NodeSpec } from './nodeSpec.types';

// Synthwave neon category palette: hot-magenta events, electric-cyan actions,
// laser-green value nodes, orange physics, gold assets/controllers.
export const C = {
  event: '#ff2e97',
  action: '#22d3ee',
  value: '#3affc0',
  physics: '#ff7043',
  assets: '#ffb454',
  objective: '#b07bff',
  fx: '#ff5bd1',
  camera: '#4f7cff',
  world: '#5be0a8',
  trigger: '#ff8a3d',
};

export const coreSpecs: Record<string, NodeSpec> = {
  'event/start': {
    kind: 'event/start',
    label: 'On Start',
    category: 'event',
    color: C.event,
    execIn: false,
    execOuts: ['out'],
    inputs: [],
    outputs: [],
  },
  'event/update': {
    kind: 'event/update',
    label: 'On Update',
    category: 'event',
    color: C.event,
    execIn: false,
    execOuts: ['out'],
    inputs: [],
    outputs: [{ id: 'dt', label: 'Δ sec', kind: 'number' }],
  },
  // Edge-triggered keyboard event: fires its exec output once, the frame `key`
  // is pressed (not every frame it's held). Drive a Branch/Log/etc. directly —
  // no On Update + Key Down (value) polling needed.
  'event/keyDown': {
    kind: 'event/keyDown',
    label: 'On Key Down',
    category: 'event',
    color: C.event,
    execIn: false,
    execOuts: ['out'],
    inputs: [],
    outputs: [],
    fields: [{ id: 'key', label: 'key', kind: 'string', default: 'space', editor: 'keycapture' }],
  },
  'action/log': {
    kind: 'action/log',
    label: 'Log',
    category: 'action',
    color: C.action,
    execIn: true,
    execOuts: ['out'],
    inputs: [{ id: 'msg', label: 'message', kind: 'string', default: 'hello' }],
    outputs: [],
  },
  'action/translate': {
    kind: 'action/translate',
    label: 'Translate',
    category: 'action',
    color: C.action,
    execIn: true,
    execOuts: ['out'],
    inputs: [{ id: 'by', label: 'by', kind: 'vec3', default: { x: 0, y: 0, z: 1 } }],
    outputs: [],
    fields: [{ id: 'perSecond', label: 'per second', kind: 'bool', default: true }],
  },
  'action/rotate': {
    kind: 'action/rotate',
    label: 'Rotate',
    category: 'action',
    color: C.action,
    execIn: true,
    execOuts: ['out'],
    inputs: [{ id: 'by', label: 'deg', kind: 'vec3', default: { x: 0, y: 45, z: 0 } }],
    outputs: [],
    fields: [{ id: 'perSecond', label: 'per second', kind: 'bool', default: true }],
  },
  'action/setPosition': {
    kind: 'action/setPosition',
    label: 'Set Position',
    category: 'action',
    color: C.action,
    execIn: true,
    execOuts: ['out'],
    inputs: [{ id: 'to', label: 'to', kind: 'vec3', default: { x: 0, y: 1, z: 0 } }],
    outputs: [],
  },
  'action/setProp': {
    kind: 'action/setProp',
    label: 'Set Property',
    category: 'action',
    color: C.action,
    execIn: true,
    execOuts: ['out'],
    // `target` is optional: leave it unconnected to set the property on this entity,
    // or wire in an object (e.g. On Collision's "other") to set it on that one.
    inputs: [
      { id: 'target', label: 'target (self)', kind: 'entity' },
      { id: 'value', label: 'value', kind: 'number', default: 0 },
    ],
    outputs: [],
    fields: [{ id: 'key', label: 'key', kind: 'string', default: 'health' }],
  },
  'action/branch': {
    kind: 'action/branch',
    label: 'Branch (if)',
    category: 'action',
    color: C.action,
    execIn: true,
    execOuts: ['then', 'else'],
    inputs: [{ id: 'cond', label: 'condition', kind: 'bool', default: true }],
    outputs: [],
  },
  'value/number': {
    kind: 'value/number',
    label: 'Number',
    category: 'value',
    color: C.value,
    execIn: false,
    execOuts: [],
    inputs: [],
    outputs: [{ id: 'out', label: 'value', kind: 'number' }],
    fields: [{ id: 'value', label: '', kind: 'number', default: 1 }],
  },
  'value/vec3': {
    kind: 'value/vec3',
    label: 'Vector3',
    category: 'value',
    color: C.value,
    execIn: false,
    execOuts: [],
    inputs: [],
    outputs: [{ id: 'out', label: 'vec', kind: 'vec3' }],
    fields: [{ id: 'value', label: '', kind: 'vec3', default: { x: 0, y: 0, z: 0 } }],
  },
  'value/position': {
    kind: 'value/position',
    label: 'Get Position',
    category: 'value',
    color: C.value,
    execIn: false,
    execOuts: [],
    inputs: [],
    outputs: [{ id: 'out', label: 'position', kind: 'vec3' }],
  },
  'value/prop': {
    kind: 'value/prop',
    label: 'Get Property',
    category: 'value',
    color: C.value,
    execIn: false,
    execOuts: [],
    // `target` optional — unconnected reads this entity's property; wire an object to read its.
    inputs: [{ id: 'target', label: 'target (self)', kind: 'entity' }],
    outputs: [{ id: 'out', label: 'value', kind: 'number' }],
    fields: [{ id: 'key', label: 'key', kind: 'string', default: 'health' }],
  },
  'value/object': {
    kind: 'value/object',
    label: 'Object',
    category: 'value',
    color: C.value,
    execIn: false,
    execOuts: [],
    inputs: [],
    outputs: [{ id: 'out', label: 'object', kind: 'entity' }],
    // Resolve an object by its name to target it from Set/Get Property.
    fields: [{ id: 'name', label: 'name', kind: 'string', default: '' }],
  },
  'value/time': {
    kind: 'value/time',
    label: 'Time',
    category: 'value',
    color: C.value,
    execIn: false,
    execOuts: [],
    inputs: [],
    outputs: [{ id: 'out', label: 'sec', kind: 'number' }],
  },
  'value/key': {
    kind: 'value/key',
    label: 'Key Down',
    category: 'value',
    color: C.value,
    execIn: false,
    execOuts: [],
    inputs: [],
    outputs: [{ id: 'out', label: 'down', kind: 'bool' }],
    fields: [{ id: 'key', label: 'key', kind: 'string', default: 'w', editor: 'keycapture' }],
  },
  'value/math': {
    kind: 'value/math',
    label: 'Math',
    category: 'value',
    color: C.value,
    execIn: false,
    execOuts: [],
    inputs: [
      { id: 'a', label: 'a', kind: 'number', default: 0 },
      { id: 'b', label: 'b', kind: 'number', default: 0 },
    ],
    outputs: [{ id: 'out', label: 'result', kind: 'number' }],
    fields: [{ id: 'op', label: 'op', kind: 'string', default: '+' }],
  },
};
