import type { NodeSpec } from './nodeSpec.types';
import { C } from './nodeSpecs.core';

export const extraSpecs: Record<string, NodeSpec> = {
  // ---------------- Physics ----------------
  'physics/setVelocity': {
    kind: 'physics/setVelocity',
    label: 'Set Velocity',
    category: 'physics',
    color: C.physics,
    execIn: true,
    execOuts: ['out'],
    inputs: [{ id: 'v', label: 'm/s', kind: 'vec3', default: { x: 0, y: 0, z: 0 } }],
    outputs: [],
  },
  'physics/applyImpulse': {
    kind: 'physics/applyImpulse',
    label: 'Apply Impulse',
    category: 'physics',
    color: C.physics,
    execIn: true,
    execOuts: ['out'],
    inputs: [{ id: 'v', label: 'impulse', kind: 'vec3', default: { x: 0, y: 5, z: 0 } }],
    outputs: [],
  },
  'physics/applyForce': {
    kind: 'physics/applyForce',
    label: 'Apply Force',
    category: 'physics',
    color: C.physics,
    execIn: true,
    execOuts: ['out'],
    inputs: [{ id: 'v', label: 'force', kind: 'vec3', default: { x: 0, y: 10, z: 0 } }],
    outputs: [],
  },
  'physics/getVelocity': {
    kind: 'physics/getVelocity',
    label: 'Get Velocity',
    category: 'physics',
    color: C.physics,
    execIn: false,
    execOuts: [],
    inputs: [],
    outputs: [{ id: 'out', label: 'm/s', kind: 'vec3' }],
  },
  'physics/isGrounded': {
    kind: 'physics/isGrounded',
    label: 'Is Grounded',
    category: 'physics',
    color: C.physics,
    execIn: false,
    execOuts: [],
    inputs: [],
    outputs: [{ id: 'out', label: 'grounded', kind: 'bool' }],
  },
  'physics/raycast': {
    kind: 'physics/raycast',
    label: 'Raycast Hit',
    category: 'physics',
    color: C.physics,
    execIn: false,
    execOuts: [],
    inputs: [],
    outputs: [{ id: 'out', label: 'hit', kind: 'bool' }],
    fields: [
      { id: 'dir', label: 'dir', kind: 'vec3', default: { x: 0, y: -1, z: 0 } },
      { id: 'length', label: 'len', kind: 'number', default: 1 },
    ],
  },
  'physics/onCollision': {
    kind: 'physics/onCollision',
    label: 'On Collision',
    category: 'physics',
    color: C.physics,
    execIn: false,
    execOuts: ['out'],
    inputs: [],
    // The object we collided with — wire into a Set/Get Property "target".
    outputs: [{ id: 'other', label: 'other obj', kind: 'entity' }],
  },

  // ---------------- Assets (plug-and-play controllers) ----------------
  'asset/playerController2D': {
    kind: 'asset/playerController2D',
    label: '2D Player Controller',
    category: 'assets',
    color: C.assets,
    execIn: false,
    execOuts: [],
    inputs: [],
    outputs: [],
    fields: [{ id: 'moveSpeed', label: 'speed', kind: 'number', default: 5 }],
  },
  'asset/firstPersonController': {
    kind: 'asset/firstPersonController',
    label: 'First-Person Controller',
    category: 'assets',
    color: C.assets,
    execIn: false,
    execOuts: [],
    inputs: [],
    outputs: [],
    fields: [
      { id: 'moveSpeed', label: 'move', kind: 'number', default: 5 },
      { id: 'sprintSpeed', label: 'sprint', kind: 'number', default: 8 },
      { id: 'jumpHeight', label: 'jump', kind: 'number', default: 1.2 },
      { id: 'mouseSensitivity', label: 'look', kind: 'number', default: 0.002 },
      { id: 'eyeHeight', label: 'eye', kind: 'number', default: 1.6 },
    ],
  },
  'asset/thirdPersonController': {
    kind: 'asset/thirdPersonController',
    label: 'Third-Person Controller',
    category: 'assets',
    color: C.assets,
    execIn: false,
    execOuts: [],
    inputs: [],
    outputs: [],
    fields: [
      { id: 'moveSpeed', label: 'move', kind: 'number', default: 5 },
      { id: 'sprintSpeed', label: 'sprint', kind: 'number', default: 8 },
      { id: 'jumpHeight', label: 'jump', kind: 'number', default: 1.2 },
      { id: 'mouseSensitivity', label: 'look', kind: 'number', default: 0.003 },
      { id: 'cameraDistance', label: 'dist', kind: 'number', default: 6 },
      { id: 'cameraHeight', label: 'height', kind: 'number', default: 3 },
    ],
  },

  // ---------------- Objectives (game goals) ----------------
  // `goal` fields pick an objective defined in the Game Design editor.
  'objective/complete': {
    kind: 'objective/complete',
    label: 'Complete Objective',
    category: 'objective',
    color: C.objective,
    execIn: true,
    execOuts: ['out'],
    inputs: [],
    outputs: [],
    fields: [{ id: 'goal', label: 'goal', kind: 'string', editor: 'objective', default: '' }],
  },
  'objective/addProgress': {
    kind: 'objective/addProgress',
    label: 'Add Progress',
    category: 'objective',
    color: C.objective,
    execIn: true,
    execOuts: ['out'],
    inputs: [{ id: 'amount', label: 'amount', kind: 'number', default: 1 }],
    outputs: [],
    fields: [{ id: 'goal', label: 'goal', kind: 'string', editor: 'objective', default: '' }],
  },
  'objective/isComplete': {
    kind: 'objective/isComplete',
    label: 'Objective Complete?',
    category: 'objective',
    color: C.objective,
    execIn: false,
    execOuts: [],
    inputs: [],
    outputs: [{ id: 'out', label: 'done', kind: 'bool' }],
    fields: [{ id: 'goal', label: 'goal', kind: 'string', editor: 'objective', default: '' }],
  },
  'objective/progress': {
    kind: 'objective/progress',
    label: 'Objective Progress',
    category: 'objective',
    color: C.objective,
    execIn: false,
    execOuts: [],
    inputs: [],
    outputs: [{ id: 'out', label: 'count', kind: 'number' }],
    fields: [{ id: 'goal', label: 'goal', kind: 'string', editor: 'objective', default: '' }],
  },

  // ---------------- Effects (VFX) ----------------
  'fx/playEffect': {
    kind: 'fx/playEffect',
    label: 'Play Effect',
    category: 'fx',
    color: C.fx,
    execIn: true,
    execOuts: ['out'],
    inputs: [],
    outputs: [],
    fields: [{ id: 'name', label: 'effect', kind: 'string', default: '' }],
  },
  'fx/stopEffect': {
    kind: 'fx/stopEffect',
    label: 'Stop Effects',
    category: 'fx',
    color: C.fx,
    execIn: true,
    execOuts: ['out'],
    inputs: [],
    outputs: [],
  },

  // ---------------- Trigger volume events (entry points) ----------------
  'trigger/onEnter': {
    kind: 'trigger/onEnter',
    label: 'On Trigger Enter',
    category: 'trigger',
    color: C.trigger,
    execIn: false,
    execOuts: ['out'],
    inputs: [],
    outputs: [{ id: 'other', label: 'object', kind: 'entity' }],
  },
  'trigger/onExit': {
    kind: 'trigger/onExit',
    label: 'On Trigger Exit',
    category: 'trigger',
    color: C.trigger,
    execIn: false,
    execOuts: ['out'],
    inputs: [],
    outputs: [{ id: 'other', label: 'object', kind: 'entity' }],
  },
  'trigger/onStay': {
    kind: 'trigger/onStay',
    label: 'On Trigger Stay',
    category: 'trigger',
    color: C.trigger,
    execIn: false,
    execOuts: ['out'],
    inputs: [],
    outputs: [{ id: 'other', label: 'object', kind: 'entity' }],
  },

  // ---------------- Camera control ----------------
  'camera/moveTo': {
    kind: 'camera/moveTo',
    label: 'Camera Move To',
    category: 'camera',
    color: C.camera,
    execIn: true,
    execOuts: ['out'],
    inputs: [{ id: 'to', label: 'to', kind: 'vec3', default: { x: 0, y: 5, z: -10 } }],
    outputs: [],
  },
  'camera/lookAt': {
    kind: 'camera/lookAt',
    label: 'Camera Look At',
    category: 'camera',
    color: C.camera,
    execIn: true,
    execOuts: ['out'],
    inputs: [{ id: 'target', label: 'target', kind: 'entity', default: '' }],
    outputs: [],
  },
  'camera/follow': {
    kind: 'camera/follow',
    label: 'Camera Follow',
    category: 'camera',
    color: C.camera,
    execIn: true,
    execOuts: ['out'],
    inputs: [{ id: 'target', label: 'target', kind: 'entity', default: '' }],
    outputs: [],
    fields: [
      { id: 'distance', label: 'dist', kind: 'number', default: 8 },
      { id: 'height', label: 'height', kind: 'number', default: 4 },
    ],
  },
  'camera/shake': {
    kind: 'camera/shake',
    label: 'Camera Shake',
    category: 'camera',
    color: C.camera,
    execIn: true,
    execOuts: ['out'],
    inputs: [],
    outputs: [],
    fields: [
      { id: 'intensity', label: 'amount', kind: 'number', default: 0.3 },
      { id: 'duration', label: 'secs', kind: 'number', default: 0.3 },
    ],
  },

  // ---------------- World / cross-entity control ----------------
  'world/setVisible': {
    kind: 'world/setVisible',
    label: 'Set Visible',
    category: 'world',
    color: C.world,
    execIn: true,
    execOuts: ['out'],
    inputs: [
      { id: 'target', label: 'object', kind: 'entity', default: '' },
      { id: 'visible', label: 'visible', kind: 'bool', default: true },
    ],
    outputs: [],
  },
  'world/setActive': {
    kind: 'world/setActive',
    label: 'Set Active',
    category: 'world',
    color: C.world,
    execIn: true,
    execOuts: ['out'],
    inputs: [
      { id: 'target', label: 'object', kind: 'entity', default: '' },
      { id: 'active', label: 'active', kind: 'bool', default: true },
    ],
    outputs: [],
  },
  'world/destroy': {
    kind: 'world/destroy',
    label: 'Destroy Object',
    category: 'world',
    color: C.world,
    execIn: true,
    execOuts: ['out'],
    inputs: [{ id: 'target', label: 'object', kind: 'entity', default: '' }],
    outputs: [],
  },
  'world/teleport': {
    kind: 'world/teleport',
    label: 'Teleport Object',
    category: 'world',
    color: C.world,
    execIn: true,
    execOuts: ['out'],
    inputs: [
      { id: 'target', label: 'object', kind: 'entity', default: '' },
      { id: 'to', label: 'to', kind: 'vec3', default: { x: 0, y: 0, z: 0 } },
    ],
    outputs: [],
  },
  'world/setVelocity': {
    kind: 'world/setVelocity',
    label: 'Set Object Velocity',
    category: 'world',
    color: C.world,
    execIn: true,
    execOuts: ['out'],
    inputs: [
      { id: 'target', label: 'object', kind: 'entity', default: '' },
      { id: 'v', label: 'm/s', kind: 'vec3', default: { x: 0, y: 8, z: 0 } },
    ],
    outputs: [],
  },
  'world/applyImpulse': {
    kind: 'world/applyImpulse',
    label: 'Impulse Object',
    category: 'world',
    color: C.world,
    execIn: true,
    execOuts: ['out'],
    inputs: [
      { id: 'target', label: 'object', kind: 'entity', default: '' },
      { id: 'v', label: 'impulse', kind: 'vec3', default: { x: 0, y: 5, z: 0 } },
    ],
    outputs: [],
  },
  'world/playEffect': {
    kind: 'world/playEffect',
    label: 'Play Effect On',
    category: 'world',
    color: C.world,
    execIn: true,
    execOuts: ['out'],
    inputs: [{ id: 'target', label: 'object', kind: 'entity', default: '' }],
    outputs: [],
    fields: [{ id: 'name', label: 'effect', kind: 'string', default: '' }],
  },
};
